version : '3'

services:
    lb:
        image: haproxy
        ports:
            - "80:80"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
    nodeapp1:
        build: .        
        environment:
            - APPID=1111
    nodeapp2:
        build: .        
        environment:
            - APPID=2222
    nodeapp3:
        build: .        
        environment:
            - APPID=3333
    nodeapp4:
        build: .        
        environment:
            - APPID=4444