version: '3.5'

services:  
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    # restart: always
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  
  # adminer:
  #   image: adminer
  #   # restart: always
  #   ports:
  #     - 8080:8080
  
volumes:
  db_data: