version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
       - postgres:/data/postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
      #POSTGRES_DB: test

volumes:
    postgres:
# docker-compose exec db psql -U test
